import AppKit
import CryptoKit
import ImageIO

nonisolated enum ClipKind: String, Codable, Sendable {
    case text
    case richText
    case url
    case image
    case pdf
    case files
}

/// Which kinds of pasteboard data the user wants recorded.
nonisolated struct CaptureOptions: OptionSet, Sendable {
    let rawValue: Int

    static let text = CaptureOptions(rawValue: 1 << 0)
    /// Formatting (RTF, HTML) that accompanies text. Has no effect without `.text`.
    static let richText = CaptureOptions(rawValue: 1 << 1)
    static let images = CaptureOptions(rawValue: 1 << 2)
    static let pdfs = CaptureOptions(rawValue: 1 << 3)
    static let files = CaptureOptions(rawValue: 1 << 4)

    static let all: CaptureOptions = [.text, .richText, .images, .pdfs, .files]

    func allows(_ type: NSPasteboard.PasteboardType) -> Bool {
        switch type {
        case .string, .URL: contains(.text)
        case .rtf, .rtfd, .html: contains(.text) && contains(.richText)
        case .png, .tiff: contains(.images)
        case .pdf: contains(.pdfs)
        default: false
        }
    }
}

/// An immutable snapshot of what was on the pasteboard at one point in time.
///
/// This is the value that gets serialised into `Clip.payload` and written back
/// to the pasteboard when the user picks a history entry.
nonisolated struct ClipContent: Codable, Equatable, Sendable {
    struct Representation: Codable, Equatable, Sendable {
        var type: String
        var data: Data
    }

    /// Ordered richest-last, the same order they are written back in.
    var representations: [Representation]
    /// File copies are kept as URLs rather than raw data so multi-file copies survive.
    var fileURLs: [URL]

    init(representations: [Representation] = [], fileURLs: [URL] = []) {
        self.representations = representations
        self.fileURLs = fileURLs
    }

    init(text: String) {
        self.init(representations: [.init(type: NSPasteboard.PasteboardType.string.rawValue, data: Data(text.utf8))])
    }
}

// MARK: - Reading

nonisolated extension ClipContent {
    /// Types Cowpy records. Anything else on the pasteboard is dropped.
    static let supportedTypes: [NSPasteboard.PasteboardType] = [
        .string, .rtf, .rtfd, .html, .URL, .pdf, .png, .tiff,
    ]

    /// Markers from nspasteboard.org that password managers and similar apps set
    /// to ask clipboard managers not to record an entry.
    static let concealedTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
    ]

    /// Returns `nil` when there is nothing worth recording.
    init?(pasteboard: NSPasteboard, ignoringConcealed: Bool = true, capturing options: CaptureOptions = .all) {
        let types = pasteboard.types ?? []
        if ignoringConcealed, types.contains(where: { Self.concealedTypes.contains($0.rawValue) }) {
            return nil
        }

        let urls = pasteboard.readObjects(
            forClasses: [NSURL.self],
            options: [.urlReadingFileURLsOnly: true]
        ) as? [URL] ?? []

        if !urls.isEmpty {
            // Finder also publishes the file name and icon; those would paste
            // instead of the file in some apps, so keep only the URLs. For the
            // same reason a file copy is dropped outright when files are off,
            // rather than recorded as its name.
            guard options.contains(.files) else { return nil }
            self.init(fileURLs: urls)
            return
        }

        var representations: [Representation] = []
        for type in Self.supportedTypes where types.contains(type) && options.allows(type) {
            guard let data = pasteboard.data(forType: type), !data.isEmpty else { continue }
            representations.append(.init(type: type.rawValue, data: data))
        }
        // PNG and TIFF of the same image double the storage for no benefit.
        if representations.contains(where: { $0.type == NSPasteboard.PasteboardType.png.rawValue }) {
            representations.removeAll { $0.type == NSPasteboard.PasteboardType.tiff.rawValue }
        }

        guard !representations.isEmpty else { return nil }
        self.init(representations: representations)
    }
}

// MARK: - Writing

nonisolated extension ClipContent {
    func write(to pasteboard: NSPasteboard, plainTextOnly: Bool = false) {
        pasteboard.clearContents()

        if !fileURLs.isEmpty {
            pasteboard.writeObjects(fileURLs as [NSURL])
            return
        }
        if plainTextOnly, let plainText {
            pasteboard.setString(plainText, forType: .string)
            return
        }

        let item = NSPasteboardItem()
        for representation in representations {
            item.setData(representation.data, forType: .init(representation.type))
        }
        pasteboard.writeObjects([item])
    }
}

// MARK: - Derived values

nonisolated extension ClipContent {
    private func data(for type: NSPasteboard.PasteboardType) -> Data? {
        representations.first { $0.type == type.rawValue }?.data
    }

    private func has(_ type: NSPasteboard.PasteboardType) -> Bool {
        data(for: type) != nil
    }

    var plainText: String? {
        data(for: .string).flatMap { String(data: $0, encoding: .utf8) }
    }

    var imageData: Data? {
        data(for: .png) ?? data(for: .tiff)
    }

    var kind: ClipKind {
        if !fileURLs.isEmpty { return .files }
        if let plainText {
            if has(.rtf) || has(.rtfd) || has(.html) { return .richText }
            if has(.URL) || Self.looksLikeWebURL(plainText) { return .url }
            return .text
        }
        if imageData != nil { return .image }
        if has(.pdf) { return .pdf }
        return has(.rtf) || has(.rtfd) || has(.html) ? .richText : .text
    }

    /// A single-line label for menus. Callers truncate to their own width.
    var title: String {
        switch kind {
        case .files:
            let names = fileURLs.map(\.lastPathComponent)
            return names.count == 1 ? names[0] : "\(names.count) files: " + names.joined(separator: ", ")
        case .image:
            if let size = imagePixelSize {
                return "Image (\(size.width) × \(size.height))"
            }
            return "Image"
        case .pdf:
            return "PDF"
        case .text, .richText, .url:
            guard let plainText else { return "Rich text" }
            return Self.singleLine(plainText).ifEmpty("(whitespace)")
        }
    }

    /// Stable identity for de-duplication: same bytes, same hash.
    var contentHash: String {
        var hasher = SHA256()
        for url in fileURLs {
            hasher.update(data: Data(url.path.utf8))
            hasher.update(data: Data([0]))
        }
        for representation in representations {
            hasher.update(data: Data(representation.type.utf8))
            hasher.update(data: Data([0]))
            hasher.update(data: representation.data)
        }
        return hasher.finalize().map { String(format: "%02x", $0) }.joined()
    }

    var imagePixelSize: (width: Int, height: Int)? {
        guard let imageData,
              let source = CGImageSourceCreateWithData(imageData as CFData, nil),
              let properties = CGImageSourceCopyPropertiesAtIndex(source, 0, nil) as? [CFString: Any],
              let width = properties[kCGImagePropertyPixelWidth] as? Int,
              let height = properties[kCGImagePropertyPixelHeight] as? Int
        else { return nil }
        return (width, height)
    }

    /// PNG thumbnail no larger than `maxPixelSize` on its longest edge.
    func thumbnailPNG(maxPixelSize: Int) -> Data? {
        guard let imageData,
              let source = CGImageSourceCreateWithData(imageData as CFData, nil)
        else { return nil }
        let options: [CFString: Any] = [
            kCGImageSourceCreateThumbnailFromImageAlways: true,
            kCGImageSourceCreateThumbnailWithTransform: true,
            kCGImageSourceThumbnailMaxPixelSize: maxPixelSize,
        ]
        guard let thumbnail = CGImageSourceCreateThumbnailAtIndex(source, 0, options as CFDictionary) else {
            return nil
        }
        return NSBitmapImageRep(cgImage: thumbnail).representation(using: .png, properties: [:])
    }

    static func singleLine(_ text: String) -> String {
        text.split(whereSeparator: \.isWhitespace).joined(separator: " ")
    }

    static func looksLikeWebURL(_ text: String) -> Bool {
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.contains(where: \.isWhitespace),
              let components = URLComponents(string: trimmed),
              let scheme = components.scheme?.lowercased(),
              scheme == "http" || scheme == "https"
        else { return false }
        return components.host?.isEmpty == false
    }
}

// MARK: - Serialisation

nonisolated extension ClipContent {
    /// Binary property list keeps `Data` as raw bytes (JSON would base64 it).
    func encoded() throws -> Data {
        let encoder = PropertyListEncoder()
        encoder.outputFormat = .binary
        return try encoder.encode(self)
    }

    init(encoded data: Data) throws {
        self = try PropertyListDecoder().decode(ClipContent.self, from: data)
    }
}

private nonisolated extension String {
    func ifEmpty(_ fallback: String) -> String { isEmpty ? fallback : self }
}
